   	drop table APPOINTMENT if exists;
    drop table USER if exists;
 

    create table USER (
        id bigint generated by default as identity,
        username varchar(255),
        password varchar(255),
        phone_number smallint,
        primary key (id)
    );

    

    


insert into USER (username, password, phone_number) values ('john', 'john', 333);
insert into USER (username, password, phone_number) values ('smith', 'smith',222);
insert into USER (username, password, phone_number) values ('peter', 'peter',555);

